version: 2
updates:
  # Python (pip-managed requirements)
  - package-ecosystem: "pip"
    directory: "/app"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    reviewers:
      - "HaiNick"
    assignees:
      - "HaiNick"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "deps"
      include: "scope"
    # Optional: group all Python bumps into fewer PRs
    groups:
      all-deps:
        patterns:
          - "*"

  # Dockerfile in /app
  - package-ecosystem: "docker"
    directory: "/app"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 3
    reviewers:
      - "HaiNick"
    assignees:
      - "HaiNick"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "docker"
      include: "scope"

  # Docker Compose at repo root
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 3
    reviewers:
      - "HaiNick"
    assignees:
      - "HaiNick"
    labels:
      - "dependencies"
      - "docker"
      - "compose"
    commit-message:
      prefix: "compose"
      include: "scope"

  # Enable when ready:
  # - package-ecosystem: "github-actions"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #     day: "monday"
  #     time: "10:00"
  #     timezone: "Europe/Berlin"
  #   open-pull-requests-limit: 3
  #   reviewers:
  #     - "HaiNick"
  #   assignees:
  #     - "HaiNick"
  #   labels:
  #     - "dependencies"
  #     - "ci"
  #   commit-message:
  #     prefix: "ci"
  #     include: "scope"