version: "3.8"

services:
  app:
    build: ./app
    expose:
      - "8000"              # internal only; do not publish
    volumes:
      - ./emails.txt:/app/emails.txt:ro
      - ./routes.json:/app/routes.json  # Persist route configuration
    environment:
      - FLASK_ENV=production
      - EMAILS_FILE_PATH=/app/emails.txt
      - LOG_FILE_PATH=/app/access.log
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; requests.get('http://localhost:8000/health').raise_for_status()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    ports:
      - "127.0.0.1:4180:4180"  # Funnel proxies to this
    env_file:
      - ./.env
    environment:
      OAUTH2_PROXY_PROVIDER: google
      OAUTH2_PROXY_SCOPE: "openid email profile"
      OAUTH2_PROXY_REDIRECT_URL: "${FUNNEL_HOST}/oauth2/callback"
      OAUTH2_PROXY_WHITELIST_DOMAINS: "${FUNNEL_HOSTNAME}"
      OAUTH2_PROXY_UPSTREAMS: "http://app:8000"
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_REVERSE_PROXY: "true"
      OAUTH2_PROXY_PASS_USER_HEADERS: "true"
      OAUTH2_PROXY_PREFER_EMAIL_TO_USER: "true"
      OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
      OAUTH2_PROXY_AUTHENTICATED_EMAILS_FILE: "/etc/oauth2-proxy/emails.txt"
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
      OAUTH2_PROXY_COOKIE_SECURE: "true"
      OAUTH2_PROXY_COOKIE_SAMESITE: "lax"
    volumes:
      - ./emails.txt:/etc/oauth2-proxy/emails.txt:ro
    depends_on:
      app:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:4180/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
